# Generated by Django 5.0 on 2023-12-24 17:39

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='global_id')),
                ('user_id', models.BigIntegerField(verbose_name='id')),
                ('market', models.CharField(choices=[('US', 'us'), ('RU', 'ru'), ('FR', 'fr'), ('PL', 'pl'), ('ES', 'es'), ('PT', 'pt'), ('TR', 'tr'), ('RO', 'ro'), ('ID', 'id'), ('HI', 'hi'), ('PH', 'ph')], max_length=5)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('nick', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ranks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('helped_users_count', models.IntegerField(default=0)),
                ('thanks_from_users', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('privileges', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderators',
            },
        ),
        migrations.CreateModel(
            name='ModeratorPreferences',
            fields=[
                ('moderator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hide_date_of_birth', models.BooleanField(default=False)),
                ('hide_friends', models.BooleanField(default=False)),
                ('send_invite_to_mentees_automatically', models.BooleanField(default=False)),
                ('invite_to_mentees_expiration_days', models.PositiveIntegerField(default=0)),
                ('receive_mentee_notification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'moderator_preferences',
            },
        ),
    ]
