# Generated by Django 5.0 on 2023-12-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='password',
        ),
    ]
